/*
* Archipelago for Half-Life (Sven Co-op) -- shared state and campaign data.
*
* checkdata.txt is generated by tools/gen_checkdata.py from the same JSON the
* apworld reads, so location ids here always match the ones the server knows.
*/

const string AP_DIR = "scripts/plugins/store/archipelago/";
const string AP_CHECKDATA = AP_DIR + "checkdata.txt";
const string AP_IN = AP_DIR + "ap_in.txt";
const string AP_OUT = AP_DIR + "ap_out.txt";

// "go back to the hub once the next map has loaded". A file rather than a global
// because the whole point is to survive the map change that is about to happen.
const string AP_PENDING = AP_DIR + "ap_pending.txt";

// "this mission is being played out, credit it once its map ends". Also a file,
// and for a sharper version of the same reason: the map it belongs to ends with
// a `game_end` and the plugin's globals do not outlive that.
const string AP_PENDING_FINALE = AP_DIR + "ap_finale.txt";

// How much DeathLink amnesty is left. Also a file, and for the same reason: the
// allowance is spent across a whole run, not a single map.
const string AP_AMNESTY = AP_DIR + "ap_amnesty.txt";

const string HUB_MAP = "-sp_campaign_portal";

// Location trigger kinds, as emitted by gen_checkdata.py.
const string TRIGGER_PICKUP = "pickup";
const string TRIGGER_KILL = "kill";
const string TRIGGER_KILL_COUNT = "kill_count";
const string TRIGGER_MAP_REACHED = "map_reached";
const string TRIGGER_CHAPTER_COMPLETE = "chapter_complete";
const string TRIGGER_CHARGER = "charger";
const string TRIGGER_WEAPON_PICKUP = "weapon_pickup";

class APChapter
{
	int index;
	string key;
	string name;
	array<string> maps;
	bool isGoal;
	// Which campaign this mission belongs to. Empty when talking to a data file
	// generated before there was more than one.
	string campaign;
	// A mission that has to be finished before this one opens, on top of
	// whatever else unlocks it. Only a finale paired with the mission before it
	// has one -- Blue Shift's outro after Power Struggle -- and it is empty
	// everywhere else, including in an older data file.
	string requiresChapter;
	// True when finishing this mission means its last map *ended*, rather than
	// that the player arrived on it.
	//
	// Arrival is the only moment a one-map finale would otherwise offer, since a
	// campaign's last map ends with `game_end` and never changes level: that is
	// what credited Blue Shift the instant a player connected to `ba_outro`.
	bool completeOnEndgame = false;

	string FirstMap() const { return maps[0]; }
	string LastMap() const { return maps[maps.length() - 1]; }

	bool HasMap( const string& in szMap ) const
	{
		for( uint i = 0; i < maps.length(); ++i )
			if( maps[i] == szMap )
				return true;
		return false;
	}
}

class APLocation
{
	int id;
	string map;
	string kind;
	string arg;          // classnames / classname / count / chapter key
	array<string> args;  // arg split on ',' for pickup lists
	string name;

	// Where it is in the world, for `!find`. Only the kinds that are a *place*
	// have one: a charger's brush centre, a weapon's spot on the floor. Reaching
	// a map is not somewhere you can be pointed at, so those have none.
	Vector position;
	bool hasPosition = false;
}

/*
* Everything the client has told us. Rebuilt from ap_in.txt on every read, so a
* map change or a plugin reload costs nothing -- the client is the source of
* truth and we are a pure view of it.
*/
class APState
{
	dictionary unlockedChapters;  // chapter key -> true
	// Missions the seed left out. Not the same as locked: no item will ever
	// unlock these, so the list says so instead of implying a key exists.
	dictionary excludedChapters;
	dictionary unlockedItems;     // AP item name -> true
	// Finales that are unsealed, by chapter key. One per campaign, because each
	// campaign's `missions_required` is its own setting and its own count.
	dictionary goalsOpen;
	// The same answer as one bool, for a client too old to send the list. True
	// only when every finale in the seed is open.
	bool goalOpen = false;
	bool connected = false;
	bool deathLink = false;
	// Deaths the lobby may take before one is reported to the multiworld.
	// 0 means every death counts, which is what an older client implies too.
	int deathLinkAmnesty = 0;
	int lastEventSeq = 0;

	bool ChapterUnlocked( const string& in szKey ) const
	{
		return unlockedChapters.exists( szKey );
	}

	bool ChapterExcluded( const string& in szKey ) const
	{
		return excludedChapters.exists( szKey );
	}

	bool ItemUnlocked( const string& in szItem ) const
	{
		return unlockedItems.exists( szItem );
	}

	/*
	* Is this campaign's finale unsealed?
	*
	* The per-chapter list when the client sends one, which it always does from
	* the version that understands more than one campaign. `goalOpen` is the
	* fallback, and it is deliberately the *all* of them rather than the any: an
	* older client cannot say which finale it means, and opening the wrong one
	* early is worse than opening the right one late.
	*/
	bool GoalOpen( const string& in szChapter ) const
	{
		if( goalsOpen.getSize() > 0 )
			return goalsOpen.exists( szChapter );
		return goalOpen;
	}
}

// --- globals --------------------------------------------------------------

array<APChapter@> g_Chapters;
array<APLocation@> g_Locations;

// Fingerprint of the id map checkdata.txt was generated from. If the client
// reports a different one, our location ids mean different things than the
// seed's do and every check we send would land on the wrong location.
string g_szDataVersion;
bool g_bDataMismatch = false;

/*
* Campaign key -> display name, and hub console -> the mission its button enters.
*
* The console table is generated rather than derived, because the campaign portal
* numbers its consoles differently in every campaign: Half-Life's are unpadded
* and start at 1 (its mission 0 has no console at all), Opposing Force's are
* zero padded and skip 06 entirely, and the rest run 01 upward. Working that out
* from a targetname is how you send a player to the wrong mission.
*/
dictionary g_CampaignNames;
dictionary g_PortalConsoles;

/*
* classname -> comma-separated campaign keys it may be granted on.
*
* They Hunger's whole arsenal is custom entities its own map scripts register,
* not weapons the game ships, so the classnames simply do not exist anywhere
* else. Handing one over on a Half-Life map asks the engine to build something it
* has never heard of. A weapon absent from this table travels anywhere.
*/
dictionary g_RestrictedClassnames;

// classname -> AP item name; a pickup of this classname is refused until owned.
dictionary g_LockedClassnames;
/*
* Classnames always granted regardless of the multiworld, and never stripped.
*
* Loaded from the `S` records as a default, then replaced by whatever the client
* sends in the snapshot: `random_starting_weapon` makes this a per-seed answer,
* so a run can open on Opposing Force's pipe wrench or They Hunger's spanner
* instead of the crowbar. An empty list from the client means "keep the file's",
* never "start with nothing" -- taking the melee weapon away from a player who
* has no other is not a state this should be able to reach.
*/
array<string> g_StartingWeapons;

// The `S` records, kept so a snapshot that carries no starting weapons can fall
// back to them without re-reading the file.
array<string> g_DefaultStartingWeapons;

/*
* Classnames this seed does not gate at all, sent by the client.
*
* Not the same as owned, which is why it is a list of its own. Owned means we
* hand it over and keep it there; ungated means we neither give it nor take it
* away, and the campaign's own pickups and .cfg loadouts decide when the player
* gets it -- exactly as Half-Life does. Empty for anything the seed shuffles,
* and empty when talking to a client too old to send the field.
*/
dictionary g_UngatedClassnames;

// Locations relevant to the map we are currently on, bucketed by trigger kind
// so the hot paths (pickup / kill) never walk all 174 entries.
array<APLocation@> g_MapPickups;
array<APLocation@> g_MapKills;
array<APLocation@> g_MapKillCounts;
array<APLocation@> g_MapChargers;

// "First time you find this weapon", at the one map Half-Life would have given
// it to you. Map-filtered like every other check: picking the same weapon up
// somewhere later in the campaign is not the moment this check is about.
array<APLocation@> g_WeaponPickups;

APState g_State;

// Checks already sent this session, so a re-entered map does not spam the client.
dictionary g_SentChecks;

/*
* What `!tracker` prints, as location id -> true.
*
* Both come from the client, which is the only side that knows: `g_SentChecks`
* is this session's sending, not the run's progress, and it forgets everything on
* a map change. A location in neither table is not in this seed at all --
* chargesanity off, or a campaign left out -- and the tracker skips those rather
* than listing a check nobody can make.
*/
dictionary g_CheckedLocations;
dictionary g_MissingLocations;

string g_szCurrentMap;
APChapter@ g_CurrentChapter = null;
int g_iMapKills = 0;

/*
* Are we actually *playing* the mission this map belongs to?
*
* False when the campaign chained us into a mission we never unlocked, and false
* while we are bouncing back to the hub. Both cases look identical to a genuine
* mission from inside MapChange -- the engine is leaving the last map of a
* chapter either way -- and treating them alike is what credited Office Complex
* the moment Unforeseen Consequences ended.
*/
bool g_bMissionActive = false;

// The same answer as `ap_pending.txt`, kept in memory as well as on disk.
//
// Two channels because the file has one failure mode with no symptom: if the
// write is refused -- the store directory locked, the disk busy -- the bounce
// silently never happens, the map the campaign carried us into counts as played,
// and it sends its "Reached" and every weapon lying around it. Globals survive a
// map change here (which is why Initialise exists to clear them), so this covers
// the ordinary case, and the file still covers a plugin reload.
//
// Deliberately *not* cleared by Initialise: it is written before the map change
// and has to be readable after it.
bool g_bPendingHubReturn = false;

// The map we asked the engine to load, and the mission we were last playing.
//
// Between them they answer "did we mean to be here", which is a different
// question from "are we allowed to be here" and the one that was missing. The
// campaign runs one mission straight into the next, and the old guard only
// bounced missions that were *locked* -- so being carried into a mission that
// happened to be unlocked read as playing it, and it sent its "Reached" and
// whatever weapons lay near the path through it.
//
// Neither is cleared by Initialise, for the same reason as the flag above: both
// are set before a map change and read after it.
string g_szIntendedMap = "";
string g_szLastChapterKey = "";

// Set just before we issue our own changelevel. A transition we asked for is
// never a mission completion: `!hub` out of a one-map mission is walking away
// from it, not finishing it.
bool g_bSelfChange = false;

// Tri-state, because the suit is announced on the transition and a map load must
// not re-announce it: -1 unknown, 0 not owned, 1 owned.
int g_iSuitOwned = -1;

// Set to g_Engine.time + a short window while a lobby wipe is in progress, so
// the deaths we cause are neither reported nor able to re-trigger the wipe.
float g_flDeathLinkImmuneUntil = 0.0f;

// Deaths still forgiven before the next one goes out to the multiworld. -1 means
// "not loaded yet"; it is filled from the amnesty setting the first time a death
// has to be judged, since the snapshot may not have arrived at map load.
int g_iAmnestyRemaining = -1;

// --- helpers --------------------------------------------------------------

void APLog( const string& in szMessage )
{
	g_Game.AlertMessage( at_console, "[AP] " + szMessage + "\n" );
}

/*
* ReadLine leaves the line ending on when the file was written by a Windows
* tool, and our Python side writes plain "\n" -- strip both so string compares
* against classnames and chapter keys behave.
*/
string APTrim( const string& in szValue )
{
	uint uiStart = 0;
	uint uiEnd = szValue.Length();

	while( uiStart < uiEnd )
	{
		string szChar = szValue.SubString( uiStart, 1 );
		if( szChar != " " && szChar != "\t" && szChar != "\r" && szChar != "\n" )
			break;
		++uiStart;
	}

	while( uiEnd > uiStart )
	{
		string szChar = szValue.SubString( uiEnd - 1, 1 );
		if( szChar != " " && szChar != "\t" && szChar != "\r" && szChar != "\n" )
			break;
		--uiEnd;
	}

	return szValue.SubString( uiStart, uiEnd - uiStart );
}

/*
* Strip the bridge's field separators out of free text.
*
* Player names and chat messages are the only values in the protocol that a
* person controls, so they are the only ones that can desync the parser.
*/
string APSanitise( const string& in szValue )
{
	string szOut;

	for( uint i = 0; i < szValue.Length(); ++i )
	{
		string szChar = szValue.SubString( i, 1 );
		if( szChar == "|" )
			szChar = "/";
		else if( szChar == "\n" || szChar == "\r" )
			szChar = " ";
		szOut += szChar;
	}

	return szOut;
}

/*
* Did checkdata.txt load? Anything that strips or gates has to check this first:
* empty tables mean "we do not know", not "nothing is allowed".
*/
bool CheckDataLoaded()
{
	return g_Chapters.length() > 0 && g_StartingWeapons.length() > 0;
}

/*
* How many campaigns this *seed* contains, which is not how many the data file
* knows about: checkdata.txt always lists all four, and a seed switches the ones
* it left out off by excluding every mission in them.
*/
uint IncludedCampaignCount()
{
	dictionary seen;

	for( uint i = 0; i < g_Chapters.length(); ++i )
	{
		APChapter@ pChapter = g_Chapters[i];
		if( !g_State.ChapterExcluded( pChapter.key ) )
			seen[ pChapter.campaign ] = true;
	}

	return seen.getSize();
}

APChapter@ ChapterByKey( const string& in szKey )
{
	for( uint i = 0; i < g_Chapters.length(); ++i )
		if( g_Chapters[i].key == szKey )
			return g_Chapters[i];
	return null;
}

APChapter@ ChapterForMap( const string& in szMap )
{
	for( uint i = 0; i < g_Chapters.length(); ++i )
		if( g_Chapters[i].HasMap( szMap ) )
			return g_Chapters[i];
	return null;
}

/*
* Is this mission sealed alongside a finale rather than opened by an item?
*
* True for whichever mission a finale names as its prerequisite: the pair is one
* ending, so the campaign's count opens both and no unlock item exists for
* either. Read off the pairing already in checkdata.txt, so this needs nothing
* new from the client and says "no" on data written before the pairing existed.
*
* Only a label. Whether it is actually open is the client's answer, sent in the
* unlocked list like any other mission.
*/
bool ChapterIsSealed( const string& in szKey )
{
	if( szKey.Length() == 0 )
		return false;

	for( uint i = 0; i < g_Chapters.length(); ++i )
	{
		if( g_Chapters[i].requiresChapter == szKey )
			return true;
	}

	return false;
}

bool ChapterPlayable( APChapter@ pChapter )
{
	if( pChapter is null )
		return false;
	if( pChapter.isGoal )
		return g_State.GoalOpen( pChapter.key );
	return g_State.ChapterUnlocked( pChapter.key );
}

/*
* Load checkdata.txt. Called once per map load; the file is small (~180 lines)
* and re-reading it keeps the plugin stateless across map changes.
*/
void LoadCheckData()
{
	g_Chapters.resize( 0 );
	g_Locations.resize( 0 );
	g_LockedClassnames.deleteAll();
	g_StartingWeapons.resize( 0 );
	g_DefaultStartingWeapons.resize( 0 );
	g_CampaignNames.deleteAll();
	g_PortalConsoles.deleteAll();
	g_RestrictedClassnames.deleteAll();
	@g_pArcade = null;
	g_SusTiers.resize( 0 );
	g_SusSections.resize( 0 );
	g_SusClasses.resize( 0 );
	g_SusAwards.resize( 0 );
	g_SusVolumes.deleteAll();
	g_SusSeal.deleteAll();

	File@ pFile = g_FileSystem.OpenFile( AP_CHECKDATA, OpenFile::READ );

	if( pFile is null || !pFile.IsOpen() )
	{
		APLog( "FATAL: could not open " + AP_CHECKDATA );
		return;
	}

	while( !pFile.EOFReached() )
	{
		string szRaw;
		pFile.ReadLine( szRaw );
		string szLine = APTrim( szRaw );
		if( szLine.Length() == 0 || szLine.SubString( 0, 1 ) == "#" )
			continue;

		array<string>@ parts = szLine.Split( "|" );
		if( parts.length() < 2 )
			continue;

		if( parts[0] == "C" && parts.length() >= 6 )
		{
			APChapter chapter;
			chapter.index = atoi( parts[1] );
			chapter.key = parts[2];
			chapter.name = parts[3];
			chapter.maps = parts[4].Split( "," );
			chapter.isGoal = parts[5] == "1";
			// Appended after the fact, so an older data file simply has none.
			if( parts.length() >= 7 )
				chapter.campaign = parts[6];
			if( parts.length() >= 8 )
				chapter.requiresChapter = parts[7];
			if( parts.length() >= 9 )
				chapter.completeOnEndgame = parts[8] == "1";
			g_Chapters.insertLast( @chapter );
		}
		else if( parts[0] == "M" && parts.length() >= 3 )
		{
			g_CampaignNames[ parts[1] ] = parts[2];
		}
		else if( parts[0] == "P" && parts.length() >= 3 )
		{
			g_PortalConsoles[ parts[1] ] = parts[2];
		}
		else if( parts[0] == "L" && parts.length() >= 6 )
		{
			APLocation location;
			location.id = atoi( parts[1] );
			location.map = parts[2];
			location.kind = parts[3];
			location.arg = parts[4];
			location.args = parts[4].Split( "," );
			location.name = parts[5];

			// Optional seventh field, "x y z". Absent for anything that is not a
			// point in the world, and absent entirely from an older data file.
			if( parts.length() >= 7 )
			{
				array<string>@ xyz = parts[6].Split( " " );
				if( xyz.length() >= 3 )
				{
					location.position = Vector(
						atoi( xyz[0] ), atoi( xyz[1] ), atoi( xyz[2] ) );
					location.hasPosition = true;
				}
			}

			g_Locations.insertLast( @location );
		}
		else if( parts[0] == "K" && parts.length() >= 3 )
		{
			g_LockedClassnames[ parts[1] ] = parts[2];
		}
		else if( parts[0] == "S" )
		{
			g_StartingWeapons.insertLast( parts[1] );
			g_DefaultStartingWeapons.insertLast( parts[1] );
		}
		else if( parts[0] == "R" && parts.length() >= 3 )
		{
			g_RestrictedClassnames[ parts[1] ] = parts[2];
		}
		else if( parts[0] == "D" )
		{
			g_szDataVersion = parts[1];
		}
		// The arcade maps. Absent from an older data file, in which case every
		// list below stays empty and Suspension is simply an unmanaged map.
		else if( parts[0] == "X" && parts.length() >= 7 )
		{
			APArcade arcade;
			arcade.key = parts[1];
			arcade.name = parts[2];
			arcade.map = parts[3];
			arcade.goalClass = parts[4];
			arcade.startSignal = parts[5];
			arcade.endSignal = parts[6];
			@g_pArcade = @arcade;
		}
		else if( parts[0] == "Y" && parts.length() >= 7 )
		{
			APTier tier;
			tier.key = parts[2];
			tier.name = parts[3];
			tier.tickets = atoi( parts[4] );
			tier.voteButton = parts[5];
			tier.ticketSignal = parts[6];
			g_SusTiers.insertLast( @tier );
		}
		else if( parts[0] == "Z" && parts.length() >= 6 )
		{
			APSection section;
			section.key = parts[2];
			section.index = atoi( parts[3] );
			section.name = parts[4];
			section.signal = parts[5];
			g_SusSections.insertLast( @section );
		}
		else if( parts[0] == "W" && parts.length() >= 7 )
		{
			APClass entry;
			entry.key = parts[2];
			entry.name = parts[3];
			entry.targetname = parts[4];
			entry.signal = parts[5];
			entry.mapGated = parts[6] == "1";
			if( parts.length() >= 8 )
				entry.portal = parts[7];
			g_SusClasses.insertLast( @entry );
		}
		else if( parts[0] == "A" && parts.length() >= 5 )
		{
			APAward award;
			award.key = parts[2];
			award.name = parts[3];
			award.deaths = atoi( parts[4] );
			g_SusAwards.insertLast( @award );
		}
		else if( parts[0] == "J" && parts.length() >= 5 )
		{
			APBox box;
			box.mins = APVectorFromString( parts[3] );
			box.maxs = APVectorFromString( parts[4] );
			g_SusVolumes[ parts[2] ] = @box;
		}
		else if( parts[0] == "G" && parts.length() >= 5 )
		{
			g_SusSeal[ parts[2] ] = parts[3] + "|" + parts[4];
		}
		else if( parts[0] == "E" && parts.length() >= 5 )
		{
			ApplyGrantRecord( parts[2], parts[3], parts[4] );
		}
	}

	pFile.Close();
	APLog( "loaded " + g_Chapters.length() + " chapters, " + g_Locations.length() + " locations" );
}

/*
* Narrow the location list down to the current map so the pickup and kill hooks
* stay cheap.
*/
void IndexCurrentMap()
{
	g_MapPickups.resize( 0 );
	g_MapKills.resize( 0 );
	g_MapKillCounts.resize( 0 );
	g_MapChargers.resize( 0 );
	g_WeaponPickups.resize( 0 );
	g_iMapKills = 0;

	for( uint i = 0; i < g_Locations.length(); ++i )
	{
		APLocation@ pLocation = g_Locations[i];
		if( pLocation.map != g_szCurrentMap )
			continue;

		if( pLocation.kind == TRIGGER_WEAPON_PICKUP )
			g_WeaponPickups.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_PICKUP )
			g_MapPickups.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_KILL )
			g_MapKills.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_KILL_COUNT )
			g_MapKillCounts.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_CHARGER )
			g_MapChargers.insertLast( pLocation );
	}
}
