"""Checks and items that older seeds still contain but new seeds never get.

Kept so a seed generated by an earlier release plays to the end on the current
plugin and client. Their ids stay reserved in `ids.json`; the apworld never
creates them, and nothing here is read during generation.
"""

# Removed locations, `{id: name as the old seeds call it}`. The client sends
# whichever of these a seed still lists as missing the moment it connects:
# nothing in the game fires them any more, and a seed that put progression on
# one would otherwise never finish.
LEGACY_LOCATIONS: dict[int, str] = {
    # An easter egg past a skylight, reachable only by stacking players.
    7720310: "Opposing Force - First Minigun",
    # Not a Blue Shift pickup at all: Sven Co-op's port adds the suit.
    7720432: "Blue Shift - First HEV Suit",
}

# Removed weapon items, `{name: (id, classname)}`. Received in an old seed, the
# weapon is granted like any other. Until then its pickup is left ungated, which
# is all a new seed ever sees of it.
LEGACY_WEAPONS: dict[str, tuple[int, str]] = {
    "Minigun": (7710063, "weapon_minigun"),
}

# Location names an older release used, `{old name: current name}`, for YAMLs
# that still spell them the old way. Weapon checks took ": " in place of " - "
# after v0.3 ("Opposing Force: First Glock"); those are derived in
# `locations.py`, so only the renames that rule does not cover are listed here.
LEGACY_LOCATION_NAMES: dict[str, str] = {
    "Opposing Force - First HEV Suit": "Opposing Force: First PCV",
}
